/* ═══════════════════════════════════════════════════════════════
   THOR – Base de données verres opticiens
   Sources : catalogues publics Essilor, Zeiss, Hoya, Novacel,
             BBGR, Shamir, Rodenstock, Nikon (tarifs indicatifs HT)
   ═══════════════════════════════════════════════════════════════ */

export type VerreType = "unifocal" | "bifocal" | "progressif" | "degressif";
export type VerreMatiere = "organique" | "polycarbonate" | "trivex" | "mineral";
export type VerreUsage = "unifocal-vl" | "unifocal-vp" | "progressif-confort" | "progressif-standard" | "progressif-premium" | "bifocal" | "lentille";

export interface Verre {
  id: string;
  marque: string;
  gamme: string;
  designation: string;
  /** Description commerciale complète — traitements, avantages, arguments de vente */
  description?: string;
  type: VerreType;
  matiere: VerreMatiere;
  /** Index de réfraction ex: 1.5 | 1.6 | 1.67 | 1.74 */
  indice: number;
  /** Traitements inclus */
  traitements: string[];
  /** Code LPPR SS (peut être vide si hors nomenclature) */
  lppr?: string;
  /** Classe SS : 1 = remboursé nomenclature / 2 = remboursé 100% santé */
  classeSS?: 1 | 2;
  /** Prix catalogue HT (indicatif — à ajuster selon contrat fournisseur) */
  prixAchatHT: number;
  /** Prix de vente conseillé TTC */
  prixVenteTTC: number;
  /** TVA applicable */
  tauxTVA: 5.5 | 20;
  /** Sphere min / max commercialisée */
  sphereMin?: number;
  sphereMax?: number;
  /** Hauteur minimale de montage (mm) pour progressifs */
  hauteurMin?: number;
  /** Mots-clés libres pour la recherche */
  tags?: string[];
}

// ─── ESSILOR ───────────────────────────────────────────────────────────────

const ESSILOR: Verre[] = [
  // ── Varilux (progressifs premium)
  {
    id: "ess-var-xr-167",
    marque: "Essilor",
    gamme: "Varilux X series",
    designation: "Varilux X 4D – Indice 1.67",
    description: "Verre progressif organique indice 1.67 avec technologie 4D — zones de vision élargie jusqu'à 120°, antireflet Crizal Sapphire UV multicouche premium, protection UV400, extrêmement mince et léger.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Crizal Sapphire UV", "UV400"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 185,
    prixVenteTTC: 520,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["haut de gamme", "flou réduit", "numérique"],
  },
  {
    id: "ess-var-xr-174",
    marque: "Essilor",
    gamme: "Varilux X series",
    designation: "Varilux X 4D – Indice 1.74",
    description: "Verre progressif organique indice 1.74 ultra-mince, technologie 4D champ visuel élargi 120°, antireflet Crizal Sapphire UV multicouche, protection UV400 totale — idéal fort myope exigeant légèreté maximale.",
    type: "progressif",
    matiere: "organique",
    indice: 1.74,
    traitements: ["Crizal Sapphire UV", "UV400"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 220,
    prixVenteTTC: 620,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["haut de gamme", "fort myope", "mince"],
  },
  {
    id: "ess-var-comfort-max-15",
    marque: "Essilor",
    gamme: "Varilux Comfort Max",
    designation: "Varilux Comfort Max – Indice 1.5",
    description: "Verre progressif organique indice 1.5, technologie W.A.V.E. pour une adaptation rapide, antireflet Crizal Easy UV anti-salissures, protection UV — confort optimal pour le premier équipement progressif.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Crizal Easy UV"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 95,
    prixVenteTTC: 260,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["confort", "premier équipement"],
  },
  {
    id: "ess-var-comfort-max-16",
    marque: "Essilor",
    gamme: "Varilux Comfort Max",
    designation: "Varilux Comfort Max – Indice 1.6",
    description: "Verre progressif organique indice 1.6 aminci, technologie W.A.V.E. 2 — grandes plages de vision nette, antireflet Crizal Easy UV avec traitement anti-salissures hydrophobe, idéal astigmate.",
    type: "progressif",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Crizal Easy UV"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 110,
    prixVenteTTC: 295,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["confort", "aminci"],
  },
  {
    id: "ess-var-comfort-max-167",
    marque: "Essilor",
    gamme: "Varilux Comfort Max",
    designation: "Varilux Comfort Max – Indice 1.67",
    description: "Verre progressif organique indice 1.67 très mince, technologie W.A.V.E. 2 champ élargi, antireflet Crizal Easy UV multicouche anti-salissures, protection UV — fort astigmate et large correction.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Crizal Easy UV"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 130,
    prixVenteTTC: 350,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["confort", "fort astigmate"],
  },
  {
    id: "ess-var-lib2-15",
    marque: "Essilor",
    gamme: "Varilux Liberty 3.0",
    designation: "Varilux Liberty 3.0 – Indice 1.5",
    description: "Verre progressif organique indice 1.5, grand couloir de progression facilitant l'adaptation, antireflet Crizal Easy UV, protection UV — entrée de gamme progressif remboursé SS classe 2.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Crizal Easy UV"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 72,
    prixVenteTTC: 190,
    tauxTVA: 20,
    hauteurMin: 18,
    tags: ["entrée de gamme", "grand couloir"],
  },
  // ── Eyezen (unifocaux connectés)
  {
    id: "ess-eyezen-start-15",
    marque: "Essilor",
    gamme: "Eyezen Start",
    designation: "Eyezen Start – Indice 1.5",
    description: "Verre unifocal connecté indice 1.5, allégement visuel intégré réduisant la fatigue numérique, filtre DrivEzr pour la nuit, antireflet Crizal Prevencia filtrant les longueurs d'onde bleue-violette nocives.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Crizal Prevencia", "DrivEzr"],
    prixAchatHT: 45,
    prixVenteTTC: 120,
    tauxTVA: 20,
    tags: ["numérique", "jeunes", "anti-fatigue"],
  },
  {
    id: "ess-eyezen-start-16",
    marque: "Essilor",
    gamme: "Eyezen Start",
    designation: "Eyezen Start – Indice 1.6",
    description: "Verre unifocal connecté indice 1.6 aminci, allégement visuel pour réduire la fatigue numérique, antireflet Crizal Prevencia filtrant la lumière bleue-violette nocive, durcissement anti-rayures.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Crizal Prevencia"],
    prixAchatHT: 58,
    prixVenteTTC: 148,
    tauxTVA: 20,
    tags: ["numérique", "anti-fatigue"],
  },
  // ── Orma (unifocaux classiques)
  {
    id: "ess-orma-15",
    marque: "Essilor",
    gamme: "Orma 1.5",
    designation: "Orma 1.5 – Anti-reflet",
    description: "Verre unifocal organique indice 1.5, traitement antireflet Crizal Easy UV anti-salissures, durcissement 2 faces, protection UV — remboursement Sécurité Sociale classe 1.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Crizal Easy UV"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 18,
    prixVenteTTC: 55,
    tauxTVA: 20,
    tags: ["entrée de gamme", "classe 1"],
  },
  {
    id: "ess-orma-16",
    marque: "Essilor",
    gamme: "Orma 1.6",
    designation: "Orma 1.6 – Anti-reflet",
    description: "Verre unifocal organique indice 1.6 aminci 20% vs 1.5, antireflet Crizal Easy UV hydrophobe anti-salissures, durcissement 2 faces, UV — remboursement SS classe 1.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Crizal Easy UV"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 25,
    prixVenteTTC: 68,
    tauxTVA: 20,
    tags: ["classe 1", "aminci"],
  },
  {
    id: "ess-thin-lite-167",
    marque: "Essilor",
    gamme: "Thin&Lite 1.67",
    designation: "Thin&Lite 1.67 – Anti-reflet",
    description: "Verre unifocal organique indice 1.67 très mince et léger (−40% d'épaisseur vs 1.5), antireflet Crizal Easy UV anti-salissures hydrophobe, durcissement renforcé 2 faces — fort myope exigeant discrétion.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Crizal Easy UV"],
    lppr: "2221002",
    classeSS: 2,
    prixAchatHT: 38,
    prixVenteTTC: 98,
    tauxTVA: 20,
    tags: ["fort myope", "mince"],
  },
  {
    id: "ess-thin-lite-174",
    marque: "Essilor",
    gamme: "Thin&Lite 1.74",
    designation: "Thin&Lite 1.74 – Anti-reflet",
    description: "Verre unifocal organique indice 1.74 ultra-mince (indice le plus élevé du marché), antireflet Crizal Easy UV premium, durcissement 2 faces — solution optimale pour corrections très élevées.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.74,
    traitements: ["Crizal Easy UV"],
    lppr: "2221002",
    classeSS: 2,
    prixAchatHT: 52,
    prixVenteTTC: 130,
    tauxTVA: 20,
    tags: ["fort myope", "très mince"],
  },
  // ── Transitions (photochromiques)
  {
    id: "ess-transitions-gen8-15",
    marque: "Essilor",
    gamme: "Transitions Gen 8",
    designation: "Transitions Gen 8 – Indice 1.5 – Gris",
    description: "Verre unifocal organique indice 1.5 photochromique Gen 8 — activation 30% plus rapide que la génération précédente, teinte grise en extérieur UV400, incolore en intérieur, antireflet Crizal Easy UV.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Crizal Easy UV", "Photochromique", "UV400"],
    prixAchatHT: 62,
    prixVenteTTC: 165,
    tauxTVA: 20,
    tags: ["photochromique", "intérieur/extérieur"],
  },
  {
    id: "ess-transitions-gen8-16",
    marque: "Essilor",
    gamme: "Transitions Gen 8",
    designation: "Transitions Gen 8 – Indice 1.6 – Brun",
    description: "Verre unifocal organique indice 1.6 aminci, photochromique Gen 8 teinte brune (contraste renforcé), activation ultra-rapide, protection UV400, antireflet Crizal Easy UV — 2 en 1 lunettes & solaires.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Crizal Easy UV", "Photochromique", "UV400"],
    prixAchatHT: 78,
    prixVenteTTC: 198,
    tauxTVA: 20,
    tags: ["photochromique", "brun"],
  },
];

// ─── ZEISS ─────────────────────────────────────────────────────────────────

const ZEISS: Verre[] = [
  // ── Individual 3 (progressifs)
  {
    id: "zss-individual3-15",
    marque: "Zeiss",
    gamme: "Progressive Individual 3",
    designation: "Zeiss Individual 3 – Indice 1.5",
    description: "Verre progressif sur mesure indice 1.5, personnalisation via i.Profiler biométrique (12 paramètres oculaires), antireflet DuraVision Platinum UV multicouche premium, protection UV totale — vision nette jusqu'aux bords.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["DuraVision Platinum", "UV Protect"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 175,
    prixVenteTTC: 490,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["personnalisé", "premium", "i.Profiler"],
  },
  {
    id: "zss-individual3-167",
    marque: "Zeiss",
    gamme: "Progressive Individual 3",
    designation: "Zeiss Individual 3 – Indice 1.67",
    description: "Verre progressif sur mesure indice 1.67 très mince, personnalisation i.Profiler 12 paramètres, antireflet DuraVision Platinum UV ultra-résistant rayures, protection UV totale, anti-salissures — fort astigmate.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["DuraVision Platinum UV", "UV Protect"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 205,
    prixVenteTTC: 570,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["personnalisé", "fort astigmate", "i.Profiler"],
  },
  {
    id: "zss-progressive-a-15",
    marque: "Zeiss",
    gamme: "Progressive A",
    designation: "Zeiss Progressive A – Indice 1.5",
    description: "Verre progressif organique indice 1.5, antireflet DuraVision BlueProtect filtrant la lumière bleue nocive des écrans, protection UV400, durcissement renforcé — standard confort visuel numérique.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["DuraVision BlueProtect", "UV400"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 110,
    prixVenteTTC: 295,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["standard", "confort visuel"],
  },
  {
    id: "zss-progressive-a-16",
    marque: "Zeiss",
    gamme: "Progressive A",
    designation: "Zeiss Progressive A – Indice 1.6",
    description: "Verre progressif organique indice 1.6 aminci, antireflet DuraVision BlueProtect anti-lumière bleue, protection UV400, durcissement — confort visuel numérique, port polyvalent intérieur/extérieur.",
    type: "progressif",
    matiere: "organique",
    indice: 1.6,
    traitements: ["DuraVision BlueProtect", "UV400"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 128,
    prixVenteTTC: 340,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["standard", "aminci"],
  },
  // ── Single Vision (unifocaux)
  {
    id: "zss-sv-clearview-15",
    marque: "Zeiss",
    gamme: "Single Vision ClearView",
    designation: "Zeiss SV ClearView – Indice 1.5",
    description: "Verre unifocal organique indice 1.5, antireflet DuraVision Platinum multicouche ultra-résistant (5× plus dur), protection UV400, anti-salissures — clarté maximale, remboursement SS classe 1.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["DuraVision Platinum", "UV400"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 28,
    prixVenteTTC: 75,
    tauxTVA: 20,
    tags: ["classe 1", "unifocal"],
  },
  {
    id: "zss-sv-clearview-16",
    marque: "Zeiss",
    gamme: "Single Vision ClearView",
    designation: "Zeiss SV ClearView – Indice 1.6",
    description: "Verre unifocal organique indice 1.6 aminci, antireflet DuraVision Platinum ultra-résistant, protection UV400, anti-salissures hydrophobe — remboursement SS classe 1, discrétion et clarté.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["DuraVision Platinum", "UV400"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 38,
    prixVenteTTC: 95,
    tauxTVA: 20,
    tags: ["classe 1", "aminci"],
  },
  {
    id: "zss-sv-clearview-167",
    marque: "Zeiss",
    gamme: "Single Vision ClearView",
    designation: "Zeiss SV ClearView – Indice 1.67",
    description: "Verre unifocal organique indice 1.67 très mince, antireflet DuraVision Platinum UV multicouche, protection UV totale intégrée dans la masse, durcissement renforcé — fort myope, esthétique optimale.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.67,
    traitements: ["DuraVision Platinum UV"],
    lppr: "2221002",
    classeSS: 2,
    prixAchatHT: 52,
    prixVenteTTC: 135,
    tauxTVA: 20,
    tags: ["classe 2", "fort myope"],
  },
  // ── PhotoFusion (photochromiques)
  {
    id: "zss-photofusion-x-15",
    marque: "Zeiss",
    gamme: "PhotoFusion X",
    designation: "Zeiss PhotoFusion X – Indice 1.5 – Gris",
    description: "Verre unifocal organique indice 1.5 photochromique nouvelle génération — activation et décoloration ultra-rapides (3× plus vite), teinte grise profonde en extérieur, UV400, antireflet DuraVision Platinum.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["DuraVision Platinum", "Photochromique", "UV400"],
    prixAchatHT: 70,
    prixVenteTTC: 188,
    tauxTVA: 20,
    tags: ["photochromique", "ultra-rapide"],
  },
  // ── SmartLife (digital lifestyle)
  {
    id: "zss-smartlife-prog-15",
    marque: "Zeiss",
    gamme: "SmartLife Progressive",
    designation: "Zeiss SmartLife Progressive – Indice 1.5",
    description: "Verre progressif digital lifestyle indice 1.5, optimisé usage smartphones et tablettes — zones de vision redéfinies pour postures numériques, antireflet DuraVision BlueProtect anti-lumière bleue nocive.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["DuraVision BlueProtect"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 145,
    prixVenteTTC: 395,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["numérique", "connecté", "jeunes presbytes"],
  },
];

// ─── HOYA ──────────────────────────────────────────────────────────────────

const HOYA: Verre[] = [
  {
    id: "hoy-sync3-15",
    marque: "Hoya",
    gamme: "Sync III",
    designation: "Hoya Sync III – Indice 1.5",
    description: "Verre unifocal anti-fatigue indice 1.5, légère puissance additionnelle intégrée soulageant l'accommodation écrans, antireflet Hi-Vision LongLife ultra-dur, filtre BlueControl anti-lumière bleue nocive.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Hi-Vision LongLife", "BlueControl"],
    prixAchatHT: 42,
    prixVenteTTC: 112,
    tauxTVA: 20,
    tags: ["anti-fatigue", "numérique", "myopie débutante"],
  },
  {
    id: "hoy-hoyalux-summit-15",
    marque: "Hoya",
    gamme: "Hoyalux iD LifeStyle V+",
    designation: "Hoyalux iD LifeStyle V+ – Indice 1.5",
    description: "Verre progressif personnalisé lifestyle indice 1.5, optimisation posturale pour activités variées, antireflet Hi-Vision LongLife ultra-résistant, filtre BlueControl lumière bleue, vision nette VL/VP.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Hi-Vision LongLife", "BlueControl"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 145,
    prixVenteTTC: 385,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["personnalisé", "lifestyle"],
  },
  {
    id: "hoy-hoyalux-summit-167",
    marque: "Hoya",
    gamme: "Hoyalux iD LifeStyle V+",
    designation: "Hoyalux iD LifeStyle V+ – Indice 1.67",
    description: "Verre progressif personnalisé indice 1.67 très mince, optimisation posturale lifestyle, antireflet Hi-Vision LongLife, filtre BlueControl, durcissement 2 faces — fort astigmate actif multi-activités.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Hi-Vision LongLife", "BlueControl"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 175,
    prixVenteTTC: 465,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["fort astigmate", "personnalisé"],
  },
  {
    id: "hoy-amplitude-15",
    marque: "Hoya",
    gamme: "Amplitude",
    designation: "Hoya Amplitude – Indice 1.5",
    description: "Verre progressif organique indice 1.5, zones de vision confortables, adaptation rapide, antireflet Hi-Vision LongLife durcissement ultra-résistant — entrée de gamme progressif rapport qualité/prix optimal.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Hi-Vision LongLife"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 88,
    prixVenteTTC: 235,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["confort", "entrée progressif"],
  },
  {
    id: "hoy-nulux-15",
    marque: "Hoya",
    gamme: "Nulux",
    designation: "Hoya Nulux – Indice 1.5",
    description: "Verre unifocal organique indice 1.5, antireflet Hi-Vision LongLife ultra-dur résistant aux rayures, anti-salissures, protection UV — remboursement Sécurité Sociale classe 1, fiabilité quotidienne.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Hi-Vision LongLife"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 20,
    prixVenteTTC: 58,
    tauxTVA: 20,
    tags: ["classe 1", "standard"],
  },
  {
    id: "hoy-nulux-16",
    marque: "Hoya",
    gamme: "Nulux",
    designation: "Hoya Nulux – Indice 1.6",
    description: "Verre unifocal organique indice 1.6 aminci, antireflet Hi-Vision LongLife résistant rayures, anti-salissures, UV — remboursement SS classe 1, discrétion supplémentaire pour correction modérée.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Hi-Vision LongLife"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 28,
    prixVenteTTC: 72,
    tauxTVA: 20,
    tags: ["classe 1", "aminci"],
  },
  {
    id: "hoy-nulux-167",
    marque: "Hoya",
    gamme: "Nulux",
    designation: "Hoya Nulux – Indice 1.67",
    description: "Verre unifocal organique indice 1.67 très mince, antireflet Hi-Vision LongLife ultra-résistant, anti-salissures, UV — classe 2 remboursée, esthétique optimale pour forte correction.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Hi-Vision LongLife"],
    lppr: "2221002",
    classeSS: 2,
    prixAchatHT: 40,
    prixVenteTTC: 102,
    tauxTVA: 20,
    tags: ["classe 2", "mince"],
  },
  {
    id: "hoy-sensity-15",
    marque: "Hoya",
    gamme: "Sensity",
    designation: "Hoya Sensity – Indice 1.5 – Gris",
    description: "Verre unifocal photochromique indice 1.5 teinte grise, technologie Sensity à activation et décoloration rapides selon luminosité, UV400, antireflet Hi-Vision LongLife — confort intérieur/extérieur.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Hi-Vision LongLife", "Photochromique", "UV400"],
    prixAchatHT: 65,
    prixVenteTTC: 168,
    tauxTVA: 20,
    tags: ["photochromique", "sensity"],
  },
  {
    id: "hoy-miyosmart",
    marque: "Hoya",
    gamme: "MiyoSmart",
    designation: "Hoya MiyoSmart – Contrôle myopie",
    description: "Verre de contrôle de la myopie pour enfants et adolescents, technologie DIMS (Defocus Incorporated Multiple Segments), efficacité cliniquement prouvée −60% de progression myopique, indice 1.6, protection UV400.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Hi-Vision LongLife", "D.I.M.S. Technology", "UV400"],
    prixAchatHT: 85,
    prixVenteTTC: 225,
    tauxTVA: 20,
    sphereMin: -10,
    sphereMax: 0,
    tags: ["contrôle myopie", "enfants", "DIMS"],
  },
];

// ─── NOVACEL ───────────────────────────────────────────────────────────────

const NOVACEL: Verre[] = [
  {
    id: "nov-attitude-15",
    marque: "Novacel",
    gamme: "Attitude",
    designation: "Novacel Attitude – Indice 1.5",
    description: "Verre progressif organique indice 1.5, antireflet Novax AR multicouche, durcissement anti-rayures 2 faces, protection UV — entrée de gamme progressif, remboursement SS classe 2, rapport qualité/prix optimal.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Novax AR"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 72,
    prixVenteTTC: 190,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["rapport qualité/prix", "entrée progressif"],
  },
  {
    id: "nov-identity-15",
    marque: "Novacel",
    gamme: "Identity",
    designation: "Novacel Identity – Indice 1.5",
    description: "Verre progressif organique indice 1.5, filtre BlueUV Capture lumière bleue nocive et UV, antireflet Novax AR multicouche, durcissement 2 faces — gamme intermédiaire, confort numérique et extérieur.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Novax AR", "BlueUV Capture"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 98,
    prixVenteTTC: 258,
    tauxTVA: 20,
    hauteurMin: 16,
    tags: ["gamme intermédiaire"],
  },
  {
    id: "nov-identity-167",
    marque: "Novacel",
    gamme: "Identity",
    designation: "Novacel Identity – Indice 1.67",
    description: "Verre progressif organique indice 1.67 très mince, filtre BlueUV Capture, antireflet Novax AR multicouche, durcissement renforcé — fort myope/astigmate, gamme intermédiaire Novacel.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Novax AR", "BlueUV Capture"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 122,
    prixVenteTTC: 320,
    tauxTVA: 20,
    hauteurMin: 16,
    tags: ["gamme intermédiaire", "fort myope"],
  },
  {
    id: "nov-zephyr-15",
    marque: "Novacel",
    gamme: "Zephyr",
    designation: "Novacel Zephyr – Indice 1.5",
    description: "Verre unifocal organique indice 1.5, traitement antireflet Novax AR multicouche, durcissement anti-rayures, anti-salissures, prix accessible — remboursement Sécurité Sociale classe 1.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Novax AR"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 16,
    prixVenteTTC: 48,
    tauxTVA: 20,
    tags: ["classe 1", "entrée de gamme"],
  },
  {
    id: "nov-zephyr-16",
    marque: "Novacel",
    gamme: "Zephyr",
    designation: "Novacel Zephyr – Indice 1.6",
    description: "Verre unifocal organique indice 1.6 aminci, antireflet Novax AR multicouche, durcissement 2 faces, anti-salissures — remboursement SS classe 1, discret et résistant.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Novax AR"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 22,
    prixVenteTTC: 60,
    tauxTVA: 20,
    tags: ["classe 1", "aminci"],
  },
  {
    id: "nov-bluecut-15",
    marque: "Novacel",
    gamme: "BlueCut",
    designation: "Novacel BlueCut – Indice 1.5",
    description: "Verre unifocal organique indice 1.5 avec filtre BlueCut intégré bloquant la lumière bleue nocive, antireflet Novax AR, protection UV400 — solution économique anti-écrans numérique.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Novax AR", "BlueCut", "UV400"],
    prixAchatHT: 30,
    prixVenteTTC: 80,
    tauxTVA: 20,
    tags: ["lumière bleue", "numérique"],
  },
];

// ─── BBGR ──────────────────────────────────────────────────────────────────

const BBGR: Verre[] = [
  {
    id: "bbgr-natrio-15",
    marque: "BBGR",
    gamme: "Natrio",
    designation: "BBGR Natrio – Indice 1.5",
    description: "Verre progressif organique indice 1.5, antireflet Satin Premium multicouche durci, protection UV, anti-salissures hydrophobe — progressif confort standard, fabrication française BBGR.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Satin Premium"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 78,
    prixVenteTTC: 205,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["confort", "standard"],
  },
  {
    id: "bbgr-natrio-167",
    marque: "BBGR",
    gamme: "Natrio",
    designation: "BBGR Natrio – Indice 1.67",
    description: "Verre progressif organique indice 1.67 très mince, antireflet Satin Premium multicouche durci, protection UV, anti-salissures — fort astigmate exigeant discrétion, fabrication française.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Satin Premium"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 102,
    prixVenteTTC: 270,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["aminci", "fort astigmate"],
  },
  {
    id: "bbgr-optim-15",
    marque: "BBGR",
    gamme: "Optim",
    designation: "BBGR Optim – Indice 1.5",
    description: "Verre progressif haut de gamme BBGR indice 1.5, personnalisation poussée, antireflet Satin Protect multicouche renforcé, protection UV, anti-salissures électrostatique — vision périphérique élargie.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Satin Protect"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 115,
    prixVenteTTC: 305,
    tauxTVA: 20,
    hauteurMin: 15,
    tags: ["haut de gamme BBGR", "personnalisé"],
  },
  {
    id: "bbgr-unifocal-15",
    marque: "BBGR",
    gamme: "Unifocal Classic",
    designation: "BBGR Unifocal Classic – Indice 1.5",
    description: "Verre unifocal organique indice 1.5, antireflet Satin Easy durcissement anti-rayures, anti-salissures, UV — remboursement Sécurité Sociale classe 1, fiable et économique.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Satin Easy"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 14,
    prixVenteTTC: 42,
    tauxTVA: 20,
    tags: ["classe 1", "entrée de gamme"],
  },
  {
    id: "bbgr-unifocal-16",
    marque: "BBGR",
    gamme: "Unifocal Classic",
    designation: "BBGR Unifocal Classic – Indice 1.6",
    description: "Verre unifocal organique indice 1.6 aminci, antireflet Satin Easy durcissement 2 faces, anti-salissures, UV — remboursement SS classe 1, discrétion et économie.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["Satin Easy"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 20,
    prixVenteTTC: 55,
    tauxTVA: 20,
    tags: ["classe 1"],
  },
];

// ─── SHAMIR ────────────────────────────────────────────────────────────────

const SHAMIR: Verre[] = [
  {
    id: "sha-autograph4-15",
    marque: "Shamir",
    gamme: "Autograph IV",
    designation: "Shamir Autograph IV – Indice 1.5",
    description: "Verre progressif haut de gamme indice 1.5, technologie Eye-Point 4 axes de personnalisation, antireflet Glacier UV+ multicouche durci, filtre BlueShield anti-lumière bleue, UV400 — vision nette 360°.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Glacier UV+", "BlueShield"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 160,
    prixVenteTTC: 430,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["haut de gamme", "Eye-Point Technology"],
  },
  {
    id: "sha-autograph4-167",
    marque: "Shamir",
    gamme: "Autograph IV",
    designation: "Shamir Autograph IV – Indice 1.67",
    description: "Verre progressif haut de gamme indice 1.67 très mince, Eye-Point Technology personnalisation avancée, antireflet Glacier UV+ ultra-résistant, filtre BlueShield, UV400 — fort astigmate premium.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Glacier UV+", "BlueShield"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 195,
    prixVenteTTC: 520,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["haut de gamme", "fort astigmate"],
  },
  {
    id: "sha-smart-3in1-15",
    marque: "Shamir",
    gamme: "Shamir Smart 3-in-1",
    designation: "Shamir Smart 3-in-1 – Indice 1.5",
    description: "Verre dégressif occupation indice 1.5, 3 zones optimisées VP/distance intermédiaire/écrans, antireflet Glacier UV+ durci, UV400 — idéal travail bureau, soulagement visuel posture assise.",
    type: "degressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Glacier UV+"],
    prixAchatHT: 95,
    prixVenteTTC: 250,
    tauxTVA: 20,
    tags: ["bureau", "occupation", "dégressif"],
  },
  {
    id: "sha-myopia-control",
    marque: "Shamir",
    gamme: "Relax",
    designation: "Shamir Relax – Anti-fatigue Indice 1.5",
    description: "Verre unifocal anti-fatigue indice 1.5, micro-addition de puissance VP soulageant l'accommodation, filtre BlueShield anti-lumière bleue, antireflet Glacier UV+, UV — presbytie débutante et travail écran.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Glacier UV+", "BlueShield"],
    prixAchatHT: 48,
    prixVenteTTC: 128,
    tauxTVA: 20,
    tags: ["anti-fatigue", "numérique", "accommodation"],
  },
];

// ─── RODENSTOCK ────────────────────────────────────────────────────────────

const RODENSTOCK: Verre[] = [
  {
    id: "rod-impression5-15",
    marque: "Rodenstock",
    gamme: "Impression 5",
    designation: "Rodenstock Impression 5 – Indice 1.5",
    description: "Verre progressif ultra-premium indice 1.5, personnalisation DNEye biométrique unique (cartographie rétinienne), antireflet Solitaire Protect Balance 2 multicouche, UV400, anti-reflets parasites — vision la plus naturelle du marché.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Solitaire Protect Balance 2", "UV400"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 195,
    prixVenteTTC: 540,
    tauxTVA: 20,
    hauteurMin: 13,
    tags: ["ultra premium", "DNEye biometrics"],
  },
  {
    id: "rod-impression5-167",
    marque: "Rodenstock",
    gamme: "Impression 5",
    designation: "Rodenstock Impression 5 – Indice 1.67",
    description: "Verre progressif ultra-premium indice 1.67 très mince, personnalisation DNEye biométrique cartographie rétinienne unique, antireflet Solitaire Protect Balance 2, UV400 — fort astigmate, qualité optique absolue.",
    type: "progressif",
    matiere: "organique",
    indice: 1.67,
    traitements: ["Solitaire Protect Balance 2", "UV400"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 230,
    prixVenteTTC: 640,
    tauxTVA: 20,
    hauteurMin: 13,
    tags: ["ultra premium", "DNEye"],
  },
  {
    id: "rod-multigressiv-15",
    marque: "Rodenstock",
    gamme: "Multigressiv MyLife",
    designation: "Rodenstock Multigressiv MyLife – Indice 1.5",
    description: "Verre progressif intermédiaire indice 1.5, optimisé pour activités lifestyle variées, antireflet Solitaire Protect multicouche durci, protection UV, anti-salissures — qualité Rodenstock accessible.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Solitaire Protect"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 118,
    prixVenteTTC: 315,
    tauxTVA: 20,
    hauteurMin: 16,
    tags: ["intermédiaire", "lifestyle"],
  },
  {
    id: "rod-cosmolit-15",
    marque: "Rodenstock",
    gamme: "Cosmolit",
    designation: "Rodenstock Cosmolit 1.5 – Unifocal",
    description: "Verre unifocal organique indice 1.5, antireflet Solitaire Protect multicouche durci résistant, anti-salissures, protection UV — remboursement SS classe 1, fiabilité de la marque Rodenstock.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["Solitaire Protect"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 22,
    prixVenteTTC: 62,
    tauxTVA: 20,
    tags: ["classe 1"],
  },
];

// ─── NIKON ─────────────────────────────────────────────────────────────────

const NIKON: Verre[] = [
  {
    id: "nik-presio-power-15",
    marque: "Nikon",
    gamme: "Presio Power",
    designation: "Nikon Presio Power – Indice 1.5",
    description: "Verre progressif premium indice 1.5, grand champ de vision nette, technologie de calcul Nikon avancée, antireflet SeeCoat Plus UV multicouche, protection UV totale, anti-salissures — confort visuel maximal.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["SeeCoat Plus UV"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 155,
    prixVenteTTC: 415,
    tauxTVA: 20,
    hauteurMin: 14,
    tags: ["premium", "grand champ"],
  },
  {
    id: "nik-presio-w-15",
    marque: "Nikon",
    gamme: "Presio W",
    designation: "Nikon Presio W – Indice 1.5",
    description: "Verre progressif intermédiaire indice 1.5, zones de vision larges et confortables, antireflet SeeCoat Plus UV multicouche durci, protection UV, anti-salissures — progressif polyvalent marque Nikon.",
    type: "progressif",
    matiere: "organique",
    indice: 1.5,
    traitements: ["SeeCoat Plus UV"],
    lppr: "2230459",
    classeSS: 2,
    prixAchatHT: 105,
    prixVenteTTC: 278,
    tauxTVA: 20,
    hauteurMin: 17,
    tags: ["intermédiaire"],
  },
  {
    id: "nik-lite-sp-15",
    marque: "Nikon",
    gamme: "Lite SP",
    designation: "Nikon Lite SP – Indice 1.5",
    description: "Verre unifocal organique indice 1.5, antireflet SeeCoat Plus UV multicouche durci, protection UV intégrée, anti-salissures — remboursement SS classe 1, robustesse quotidienne marque Nikon.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["SeeCoat Plus UV"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 19,
    prixVenteTTC: 52,
    tauxTVA: 20,
    tags: ["classe 1"],
  },
  {
    id: "nik-lite-sp-16",
    marque: "Nikon",
    gamme: "Lite SP",
    designation: "Nikon Lite SP – Indice 1.6",
    description: "Verre unifocal organique indice 1.6 aminci, antireflet SeeCoat Plus UV multicouche, protection UV, anti-salissures — remboursement SS classe 1, profil discret pour correction modérée.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.6,
    traitements: ["SeeCoat Plus UV"],
    lppr: "2221001",
    classeSS: 1,
    prixAchatHT: 27,
    prixVenteTTC: 68,
    tauxTVA: 20,
    tags: ["classe 1", "aminci"],
  },
  {
    id: "nik-transitions-15",
    marque: "Nikon",
    gamme: "Transitions Signature",
    designation: "Nikon + Transitions Signature – Indice 1.5",
    description: "Verre unifocal organique indice 1.5 photochromique Transitions Signature, activation rapide UV400, antireflet SeeCoat Plus UV durci, teinte variable lumière/obscurité — confort visuel intérieur/extérieur.",
    type: "unifocal",
    matiere: "organique",
    indice: 1.5,
    traitements: ["SeeCoat Plus UV", "Photochromique", "UV400"],
    prixAchatHT: 68,
    prixVenteTTC: 178,
    tauxTVA: 20,
    tags: ["photochromique"],
  },
];

// ─── Export agrégé ──────────────────────────────────────────────────────────

export const VERRES_DB: Verre[] = [
  ...ESSILOR,
  ...ZEISS,
  ...HOYA,
  ...NOVACEL,
  ...BBGR,
  ...SHAMIR,
  ...RODENSTOCK,
  ...NIKON,
];

export const MARQUES_VERRES = ["Essilor", "Zeiss", "Hoya", "Novacel", "BBGR", "Shamir", "Rodenstock", "Nikon"] as const;
export type MarqueVerre = (typeof MARQUES_VERRES)[number];

// ─── Utilitaires de recherche ───────────────────────────────────────────────

export function searchVerres(query: string, filters?: {
  marque?: string;
  type?: VerreType;
  indice?: number;
  classeSS?: 1 | 2;
}): Verre[] {
  const q = query.toLowerCase().trim();
  return VERRES_DB.filter((v) => {
    if (filters?.marque && v.marque !== filters.marque) return false;
    if (filters?.type && v.type !== filters.type) return false;
    if (filters?.indice && v.indice !== filters.indice) return false;
    if (filters?.classeSS && v.classeSS !== filters.classeSS) return false;
    if (!q) return true;
    return (
      v.designation.toLowerCase().includes(q) ||
      v.marque.toLowerCase().includes(q) ||
      v.gamme.toLowerCase().includes(q) ||
      (v.tags ?? []).some((t) => t.toLowerCase().includes(q))
    );
  });
}

export function getVerresByMarque(marque: string): Verre[] {
  return VERRES_DB.filter((v) => v.marque === marque);
}

export function getVerresProgressifs(): Verre[] {
  return VERRES_DB.filter((v) => v.type === "progressif");
}

export function getVerresUnifo(): Verre[] {
  return VERRES_DB.filter((v) => v.type === "unifocal");
}

export function getVerresByClasse(classe: 1 | 2): Verre[] {
  return VERRES_DB.filter((v) => v.classeSS === classe);
}
